---
title: "COVID SL FLEXDASHBOARD"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---
<<<<<<< HEAD
```{r, echo = F, include = F}
library(tidyverse)
source("flexdashboard-setup.R")
```


HOME 
=====================================
`r my_args$intro_text`

Row {data-heigth=150}
-------------------------------------
### Key facts
```{r}
```
Row {data-height=700}
=======

HOME {data-orientation=columns}
=====================================
Column {data-width=800}
>>>>>>> Initial flexboard setup
-------------------------------------
### FT plot
```{r}
```
<<<<<<< HEAD
### Other plot
```{r}
```
Row {data-height=150}
-------------------------------------
`r my_args$intro_note`

SL1{data-navmenu='TIME SERIES'}
=======
Column {data-width=200}
-------------------------------------
### Key facts
```{r}
```
TIME SERIES{data-navmenu=SL1}
>>>>>>> Initial flexboard setup
=====================================
Row{data-height=800 .tabset}
-------------------------------------
### NATIONAL
```{r}
```
### REGIONAL
```{r}
```

Row{data-height=200}
-------------------------------------
### Description of measures

```{r}
```
<<<<<<< HEAD
SL1{data-navmenu='MAPS'}
=======
MAPS{data-navmenu=SL1}
>>>>>>> Initial flexboard setup
=====================================
Row{data-height=800}
-------------------------------------
### PLOTS
```{r}
```
Row{data-height=800}
-------------------------------------
### Description of measures
```{r}
```
<<<<<<< HEAD
SL1{data-navmenu='ALL DATA'}
=======
ALL DATA{data-navmenu=SL1}
>>>>>>> Initial flexboard setup
======================================
### KABLE FOR DATA DOWNLOAD
```{r}
```
<<<<<<< HEAD
SL2{data-navmenu='TIME SERIES'}
=======
TIME SERIES{data-navmenu=SL2}
>>>>>>> Initial flexboard setup
=====================================
Row{data-height=800 .tabset}
-------------------------------------
### NATIONAL
```{r}
```

### REGIONAL
```{r}
```


Row{data-height=200}
-------------------------------------
### Description of measures

```{r}
```

<<<<<<< HEAD
SL2{data-navmenu=MAPS}
=======
MAPS{data-navmenu=SL2}
>>>>>>> Initial flexboard setup
=====================================
Row{data-height=800}
-------------------------------------
### PLOTS
```{r}
```
Row{data-height=800}
-------------------------------------
### Description of measures
```{r}
```
<<<<<<< HEAD
SL2{data-navmenu='ALL DATA'}
=======
ALL DATA{data-navmenu=SL2}
>>>>>>> Initial flexboard setup
======================================
### KABLE FOR DATA DOWNLOAD
```{r}
```
AGGREGATION
=====================================
### Still coming soon
