---
params:
    set_title: "x"
    set_subtitle: "y"
    set_author: "a"
title: "`r params$set_title`"
subtitle: "`r params$set_subtitle`"
author: "`r params$author`"
output: 
  html_document
---


```{r, include=FALSE, echo = FALSE}

knitr::opts_chunk$set(echo = FALSE)
```


```{r checks, warning = FALSE, message = FALSE, echo = FALSE}
# CHECKS
if(!exists("my_data")) stop("my_data missing")
if(!exists("my_vars")) stop("my_vars missing")
if(!exists("my_args")) stop("my_args missing")

  if(is.null(title)) title <- my_args$title
  if(is.null(title)) title <- "No title provided"

  if(is.null(subtitle)) subtitle <- my_args$subtitle
  if(is.null(subtitle)) subtitle <- " "

  if(is.null(author)) author <- my_args$author
  if(is.null(author)) author <- " "

if(!all(c("date", "id") %in% names(my_data))) stop("my_data should include date and id variables")

my_data <- mutate(my_data, date = as.Date(date))
```

`r my_args$intro_text`^[`r my_args$intro_note`]

---

```{r prep_maps, warning = FALSE, message = FALSE, echo = FALSE}
families   <- my_vars %>% pull(family) %>% unique
n_families <- length(families)
k          <- 1
vars_used  <- my_vars %>% filter(!is.na(variable)) %>% pull(variable)
vars_used  <-c("start", "district", vars_used)


# Prep maps

if (!isTRUE(gpclibPermitStatus())){
  gpclibPermit()
}

shp <- readOGR(dsn = map_path, 
               layer=map_layer, 
               verbose=FALSE, 
               stringsAsFactors = FALSE) 

shp_df <- broom::tidy(shp, region = map_region)

```


#   {.tabset .tabset-pills}

```{r, child = childRmd, echo = FALSE, eval = k>0}

```


## All Data  {.tabset  .tabset-pills}

`r my_args$data_note`

### Browse data  {.tabset}

```{r datatable, echo = FALSE, message = FALSE, warning = FALSE}

my_data %>%
 group_by(id, date) %>% mutate(obs = n()) %>% ungroup %>%
 group_by(id, date)  %>%
 summarise_all( function(x)  mean(x, na.rm = T)) %>% 
 mutate_if(is.numeric, ~round(., 3)) %>%
  datatable(caption = paste('Data to date,', group, 'level'), 
          rownames = TRUE, 
          extensions = c('Buttons', 'Scroller', 'ColReorder', 'FixedColumns'), 
          options = list(colreorder = TRUE, 
                         dom = 'Bfrtip',
                         buttons = c('copy', 'csv', 'excel'),
                         deferRender = TRUE,
                         scrollY = 200,
                         scroller = TRUE,
                         scrollX = TRUE
#          fixedColumns = list(leftColumns = 1)
  )) 
```

### Data summaries  {.tabset}

**Technical**: Summary measures on all data.

```{r summaries, warning = FALSE, echo = FALSE}
skimr::skim(my_data)
```

# 

---

Notes
